name: RestaurantApp
options:
  bundleIdPrefix: com.example
targets:
  RestaurantApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: RestaurantApp
    info:
      path: Info.plist
      properties:
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchStoryboardName: LaunchScreen
        CFBundleDisplayName: RestaurantApp
    attributes:
      LastSwiftMigration: 1500
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
